DEFAULT_CATEGORY_TYPE = "expense"
CATEGORY_TYPES = (
    (DEFAULT_CATEGORY_TYPE, "Gastos"),
    ("income", "Ingresos"),
)

DEFAULT_ACCOUNT_TYPE = "cash"
DEBIT_TYPE = "debit"
CREDIT_TYPE = "credit"
ACCOUNT_TYPES = (
    (DEFAULT_ACCOUNT_TYPE, "Efectivo"),
    (DEBIT_TYPE, "Debito"),
    (CREDIT_TYPE, "Crédito"),
)

DEFAULT_TRANSACTION_TYPE = "expense"
TRANSFER_TRANSACTION_TYPE = "transfer"
INCOME_TRANSACTION_TYPE = "income"
INSTALLMENTS_TRANSACTION_TYPE = "installments_expense"
INCOME_SAVINGS_TRANSACTION_TYPE = "savings_income"
EXPENSE_SAVINGS_TRANSACTION_TYPE = "savings_expense"
TRANSACTION_TYPES = (
    (DEFAULT_TRANSACTION_TYPE, "Gasto"),
    (INSTALLMENTS_TRANSACTION_TYPE, "Gasto a Cuotas"),
    (INCOME_TRANSACTION_TYPE, "Ingreso"),
    (TRANSFER_TRANSACTION_TYPE, "Transferencia"),
    (INCOME_SAVINGS_TRANSACTION_TYPE, "Ingreso de Ahorro"),
    (EXPENSE_SAVINGS_TRANSACTION_TYPE, "Gasto de Ahorro"),
)
MIN_INSTALLMENTS = 2
MAX_INSTALLMENTS = 12
