# Generated by Django 6.0.2 on 2026-02-25 04:13

from django.db import migrations, models

import luckydash.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    luckydash.models.UIDField(
                        auto_created=True,
                        db_index=True,
                        editable=False,
                        max_length=255,
                        prefix="membership",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Propietario"),
                            ("admin", "Administrador"),
                            ("member", "Miembro"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    luckydash.models.UIDField(
                        auto_created=True,
                        db_index=True,
                        editable=False,
                        max_length=255,
                        prefix="tenant",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("free", "Gratis"),
                            ("free_test", "Prueba gratuita"),
                            ("paid", "Pago"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
