# Generated by Django 6.0.2 on 2026-03-05 08:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import luckydash.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    luckydash.models.UIDField(
                        auto_created=True,
                        db_index=True,
                        editable=False,
                        max_length=255,
                        prefix="account",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El color debe ser un código HEX "
                                "válido como #FFF ó #FFFFFF",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("debit", "Debito"),
                            ("credit", "Crédito"),
                        ],
                        default="cash",
                        max_length=255,
                    ),
                ),
                (
                    "savings",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "billing_date",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "payment_deadline",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    luckydash.models.UIDField(
                        auto_created=True,
                        db_index=True,
                        editable=False,
                        max_length=255,
                        prefix="category",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El color debe ser un código HEX "
                                "válido como #FFF ó #FFFFFF",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("expenses", "Gastos"), ("income", "Ingresos")],
                        default="expenses",
                        max_length=255,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    luckydash.models.UIDField(
                        auto_created=True,
                        db_index=True,
                        editable=False,
                        max_length=255,
                        prefix="ticket",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(max_length=255)),
                ("purchase_date", models.DateTimeField()),
                ("approval_date", models.DateTimeField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finances.account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    luckydash.models.UIDField(
                        auto_created=True,
                        db_index=True,
                        editable=False,
                        max_length=255,
                        prefix="transaction",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("expense", "Gasto"),
                            ("income", "Ingreso"),
                            ("transfer", "Transferencia"),
                            ("savings_expense", "Ingreso de Ahorro"),
                            ("savings_income", "Gasto de Ahorro"),
                        ],
                        default="expense",
                        max_length=255,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(max_length=255)),
                ("purchase_date", models.DateTimeField()),
                ("installments", models.PositiveSmallIntegerField(null=True)),
                ("installment_number", models.PositiveSmallIntegerField(null=True)),
                ("approval_date", models.DateTimeField(null=True)),
                ("is_monthly", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finances.category",
                    ),
                ),
                (
                    "from_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transactions",
                        to="finances.account",
                    ),
                ),
                (
                    "parent_transaction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_transactions",
                        to="finances.transaction",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finances.ticket",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transactions",
                        to="finances.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
