# Generated by Django 6.0.2 on 2026-06-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_alter_account_amount_alter_account_billing_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("expense", "Gastos"), ("income", "Ingresos")],
                default="expense",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="approval_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="purchase_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="approval_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="purchase_date",
            field=models.DateField(),
        ),
    ]
