# Generated by Django 6.0.2 on 2026-08-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_alter_category_type_alter_ticket_approval_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="credit_available",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("expense", "Gasto"),
                    ("installments_expense", "Gasto a Cuotas"),
                    ("income", "Ingreso"),
                    ("transfer", "Transferencia"),
                    ("savings_income", "Ingreso de Ahorro"),
                    ("savings_expense", "Gasto de Ahorro"),
                ],
                default="expense",
                max_length=255,
            ),
        ),
    ]
